# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nqykl's blog 简单 快乐 交流
email: 8386948@qq.com
description: > # this means to ignore newlines until "baseurl:"
  生活赋予我们一种巨大的和无限高贵的礼品，这就是青春：充满着力量，充满着期待志愿，充满着求知和斗争的志向，充满着希望信心和青春
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nqykl.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  nqykl

# Build settings
markdown: kramdown